(function(){
  const STORAGE_KEYS={backend:'extensionBackupBackend',githubRepo:'extensionBackupGithubRepo',githubBranch:'extensionBackupGithubBranch',githubFolder:'extensionBackupGithubFolder',webdavUrl:'extensionBackupWebdavUrl',webdavFolder:'extensionBackupWebdavFolder',webdavUsername:'extensionBackupWebdavUsername',webdavPassword:'extensionBackupWebdavPassword'};
  const DEFAULTS={backend:'disabled',githubRepo:'',githubBranch:'',githubFolder:'chromium-cloud-sync/extensions',webdavUrl:'',webdavFolder:'/ChromiumCloudSync/extensions',webdavUsername:'',webdavPassword:''};
  const MAX_REGULAR_GITHUB_BYTES=25*1024*1024;
  const MAX_GITHUB_CONTENTS_BYTES=95*1024*1024;
  const $=id=>document.getElementById(id);
  const getSettings=()=>CCSyncRuntime.storageGet(Object.values(STORAGE_KEYS));
  const setSettings=v=>CCSyncRuntime.storageSet(v);
  const text=(key)=>{
    const zh=(window.CCSyncI18n?.currentLanguage?.()||document.documentElement.lang)==='zh-CN';
    const d={
      title:zh?'第三方扩展文件存储':'Third-party extension file storage',
      desc:zh?'CRX / ZIP 不再写入 Gist。请选择 GitHub 私有仓库或 WebDAV 作为独立文件存储。':'CRX / ZIP packages are stored outside the sync Gist. Choose a GitHub private repository or WebDAV file store.',
      backend:zh?'存储后端':'Storage backend', disabled:zh?'不使用文件备份':'Disabled', github:zh?'GitHub 私有仓库':'GitHub private repository', webdav:'WebDAV',
      repo:zh?'GitHub 仓库':'GitHub repository', branch:zh?'分支（可选）':'Branch (optional)', folder:zh?'存储文件夹':'Storage folder', repoHint:zh?'例如：用户名/仓库名':'e.g. owner/repository',
      davUrl:zh?'WebDAV 地址':'WebDAV URL', davFolder:zh?'WebDAV 文件夹':'WebDAV folder', user:zh?'用户名':'Username', pass:zh?'密码':'Password',
      test:zh?'测试连接':'Test connection', save:zh?'保存存储设置':'Save storage settings', saved:zh?'存储设置已保存':'Storage settings saved', tested:zh?'连接成功':'Connection successful',
      disabledSaved:zh?'已关闭第三方扩展文件备份。':'Third-party extension file backups are disabled.',
      lfs:zh?'较大的 CRX / ZIP 建议使用 Git LFS。当前浏览器端 GitHub 上传走普通 Contents API；超过 25 MB 会提示，超过 95 MB 将被拒绝。':'For larger CRX / ZIP packages, Git LFS is recommended. Browser-side GitHub uploads currently use the regular Contents API; files over 25 MB get a warning and files over 95 MB are rejected.',
      perm:zh?'WebDAV 需要允许访问你填写的服务器地址。':'WebDAV requires permission to access the server origin you enter.',
      needRepo:zh?'请输入 GitHub 仓库，格式为 owner/repository。':'Enter a GitHub repository in owner/repository format.',
      needDav:zh?'请输入 WebDAV 地址。':'Enter a WebDAV URL.', badRepo:zh?'无法写入这个仓库，请确认 Token 具有 Contents 写入权限。':'This repository is not writable. Make sure the Token has Contents write permission.', invalid:zh?'不支持的存储后端。':'Unsupported storage backend.'
    }; return d[key]||key;
  };
  const escape=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;};
  function safeSegment(v){return String(v||'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)||'extension';}
  function normalizeRepo(v){return String(v||'').trim().replace(/^https?:\/\/github\.com\//i,'').replace(/\.git$/i,'').replace(/^\/+|\/+$/g,'');}
  function normalizeFolder(v){return String(v||'').trim().replace(/^\/+|\/+$/g,'').replace(/\/+/g,'/');}
  function normalizeDavFolder(v){let x=String(v||'').trim().replace(/\\/g,'/');if(!x)x='/';if(!x.startsWith('/'))x='/'+x;return x.replace(/\/+/g,'/').replace(/\/$/,'')||'/';}
  function joinPath(...parts){return parts.filter(Boolean).map((p,i)=>i===0?String(p).replace(/\/+$/,''):String(p).replace(/^\/+|\/+$/g,'')).filter(Boolean).join('/');}
  function formatBytes(n){if(n<1024)return `${n} B`;if(n<1024*1024)return `${(n/1024).toFixed(1)} KB`;return `${(n/(1024*1024)).toFixed(1)} MB`;}
  function bytesToBase64(bytes){let s='';const c=0x8000;for(let i=0;i<bytes.length;i+=c)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+c,bytes.length)));return btoa(s);}
  function bytesToUtf8(bytes){return new TextDecoder().decode(bytes);}
  function base64BytesForBasicAuth(value){return bytesToBase64(new TextEncoder().encode(value));}
  async function sha256(bytes){const d=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
  async function requestDavPermission(url){const u=new URL(url);const origin=`${u.origin}/*`;if(!chrome.permissions?.request)return true;const already=await chrome.permissions.contains({origins:[origin]});return already||await chrome.permissions.request({origins:[origin]});}
  function authHeader(user,password){return user||password?`Basic ${base64BytesForBasicAuth(`${user}:${password}`)}`:'';}

  async function githubRequest(path,options={}){
    const s=await CCSyncRuntime.storageGet(['githubToken']);const token=String(s.githubToken||'').trim();if(!token)throw Error('GitHub Token is not configured.');
    const r=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',Authorization:`Bearer ${token}`,...(options.headers||{})}});
    const raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{data={raw};}
    if(!r.ok){const e=new Error(data?.message||`GitHub API HTTP ${r.status}`);e.status=r.status;throw e;}return {data,headers:r.headers};
  }
  async function githubRepoInfo(cfg){const repo=normalizeRepo(cfg.githubRepo);if(!/^[^/]+\/[^/]+$/.test(repo))throw Error(text('needRepo'));const r=await githubRequest(`/repos/${repo}`);if(r.data.private===false)throw Error('The configured repository must be private.');if(r.data.permissions&&!r.data.permissions.push)throw Error(text('badRepo'));return r.data;}
  async function githubFile(repo,path){try{return (await githubRequest(`/repos/${repo}/contents/${path}`)).data;}catch(e){if(e.status===404)return null;throw e;}}
  async function githubPutFile(cfg,path,bytes,message){if(bytes.length>MAX_GITHUB_CONTENTS_BYTES)throw Error(`File too large for the browser-side GitHub Contents API: ${formatBytes(bytes.length)}.`);const repo=normalizeRepo(cfg.githubRepo);const existing=await githubFile(repo,path);const body={message,content:bytesToBase64(bytes),branch:cfg.githubBranch||undefined};if(existing?.sha)body.sha=existing.sha;await githubRequest(`/repos/${repo}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}
  async function githubGetBytes(cfg,path){const repo=normalizeRepo(cfg.githubRepo);const r=await githubRequest(`/repos/${repo}/contents/${path}`,{headers:{Accept:'application/vnd.github.raw+json'}});if(r.data instanceof ArrayBuffer)return new Uint8Array(r.data);if(typeof r.data==='string')return new TextEncoder().encode(r.data);throw Error('GitHub raw file response was not readable.');}
  async function githubJson(cfg,path,fallback){const f=await githubFile(normalizeRepo(cfg.githubRepo),path);if(!f)return fallback;const r=await fetch(f.download_url,{headers:{Authorization:`Bearer ${(await CCSyncRuntime.storageGet(['githubToken'])).githubToken||''}`}});if(!r.ok)throw Error(`GitHub metadata download failed: HTTP ${r.status}`);return r.json();}
  async function githubWriteIndex(cfg,index){await githubPutFile(cfg,joinPath(normalizeFolder(cfg.githubFolder),'index.json'),new TextEncoder().encode(JSON.stringify(index,null,2)),'Update extension backup index');}
  async function webdavRequest(cfg,relative,options={}){const ok=await requestDavPermission(cfg.webdavUrl);if(!ok)throw Error(text('perm'));const base=cfg.webdavUrl.replace(/\/+$/,'');const folder=normalizeDavFolder(cfg.webdavFolder);const url=`${base}${folder==='/'?'':folder}/${String(relative||'').replace(/^\/+/, '')}`;const headers={...(options.headers||{})};const a=authHeader(cfg.webdavUsername,cfg.webdavPassword);if(a)headers.Authorization=a;const r=await fetch(url,{...options,headers});return r;}
  async function webdavEnsureFolder(cfg,folder){const normalized=normalizeDavFolder(folder);if(normalized==='/')return;const parts=normalized.split('/').filter(Boolean);let current='';for(const part of parts){current+='/'+part;const r=await webdavRequest(cfg,'',{method:'MKCOL',headers:{'X-WebDAV-Path':current}}).catch(e=>{throw e;});if(![200,201,204,207,405,409].includes(r.status)){const body=await r.text();if(r.status!==404)throw Error(`WebDAV MKCOL failed: HTTP ${r.status} ${body}`);} }}
  async function webdavPut(cfg,relative,bytes,contentType='application/octet-stream'){const folder=String(relative||'').replace(/^\/+/, '').split('/').slice(0,-1).join('/');await webdavEnsureFolder(cfg,joinPath(normalizeDavFolder(cfg.webdavFolder),folder));const r=await webdavRequest(cfg,relative,{method:'PUT',headers:{'Content-Type':contentType},body:bytes});if(!r.ok)throw Error(`WebDAV upload failed: HTTP ${r.status}`);}
  async function webdavGet(cfg,relative){const r=await webdavRequest(cfg,relative,{method:'GET'});if(!r.ok)throw Error(`WebDAV download failed: HTTP ${r.status}`);return new Uint8Array(await r.arrayBuffer());}
  async function webdavExists(cfg,relative){const r=await webdavRequest(cfg,relative,{method:'GET'});if(r.status===404)return null;if(!r.ok)throw Error(`WebDAV metadata read failed: HTTP ${r.status}`);return new Uint8Array(await r.arrayBuffer());}

  async function readIndex(cfg){const file='index.json';try{if(cfg.backend==='github')return await githubJson(cfg,joinPath(normalizeFolder(cfg.githubFolder),file),{schemaVersion:1,backups:[]});const b=await webdavGet(cfg,file);return JSON.parse(bytesToUtf8(b));}catch(e){if(e.status===404||String(e.message||'').includes('HTTP 404'))return {schemaVersion:1,backups:[]};throw e;}}
  async function writePackage(cfg,extension,fileBytes,fileName){const sha=await sha256(fileBytes);const extId=safeSegment(extension.id);const ver=safeSegment(extension.version||'unknown');const folder=joinPath('extensions',extId,`v${ver}`);const packagePath=joinPath(folder,safeSegment(fileName));const metadata={schemaVersion:1,type:'chromium-cloud-sync-extension-package',extension:{id:extension.id,name:extension.name||extension.id,version:extension.version||''},package:{path:packagePath,fileName,format:/\.crx$/i.test(fileName)?'crx':'zip',size:fileBytes.length,sha256:sha,storedAt:new Date().toISOString()}};if(cfg.backend==='github'){
      const root=normalizeFolder(cfg.githubFolder);await githubPutFile(cfg,joinPath(root,packagePath),fileBytes,`Back up ${extension.name||extension.id} v${extension.version||''}`);await githubPutFile(cfg,joinPath(root,folder,'metadata.json'),new TextEncoder().encode(JSON.stringify(metadata,null,2)),'Update extension backup metadata');
    }else{
      await webdavPut(cfg,packagePath,fileBytes,'application/octet-stream');await webdavPut(cfg,joinPath(folder,'metadata.json'),new TextEncoder().encode(JSON.stringify(metadata,null,2)),'application/json');
    }
    const index=await readIndex(cfg);const key=`${extension.id}:${extension.version}:${sha}`;const backups=(index.backups||[]).filter(x=>`${x.extensionId}:${x.version}:${x.sha256}`!==key);backups.push({extensionId:extension.id,name:extension.name||extension.id,version:extension.version||'',fileName,format:metadata.package.format,size:fileBytes.length,sha256:sha,path:packagePath,storedAt:metadata.package.storedAt});index.schemaVersion=1;index.updatedAt=new Date().toISOString();index.backups=backups.slice(-200);if(cfg.backend==='github')await githubWriteIndex(cfg,index);else await webdavPut(cfg,'index.json',new TextEncoder().encode(JSON.stringify(index,null,2)),'application/json');return metadata;}
  async function loadPackage(cfg,item){return cfg.backend==='github'?githubGetBytes(cfg,joinPath(normalizeFolder(cfg.githubFolder),item.path)):webdavGet(cfg,item.path);}
  async function testBackend(cfg){if(cfg.backend==='disabled')return true;if(cfg.backend==='github'){await githubRepoInfo(cfg);return true;}if(cfg.backend==='webdav'){if(!cfg.webdavUrl)throw Error(text('needDav'));const u=new URL(cfg.webdavUrl);const ok=await requestDavPermission(u.toString());if(!ok)throw Error(text('perm'));const r=await webdavRequest(cfg,'index.json',{method:'GET'});if(![200,206,404].includes(r.status))throw Error(`WebDAV connection failed: HTTP ${r.status}`);return true;}throw Error(text('invalid'));}
  async function getConfig(){const s=await getSettings();return {...DEFAULTS,...s};}

  function injectStyles(){if($('ccsExtensionStorageStyles'))return;const style=document.createElement('style');style.id='ccsExtensionStorageStyles';style.textContent=`
    .extension-storage-grid{display:grid;gap:10px}.extension-storage-grid .field-label{gap:5px}.extension-storage-grid .span-2{grid-column:1/-1}.extension-storage-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.extension-storage-note{margin:8px 0 0;font-size:12px;line-height:1.55;color:var(--text-2)}
    .extension-storage-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--line)}.extension-storage-main{min-width:0}.extension-storage-name{font-size:13px;font-weight:600;overflow-wrap:anywhere}.extension-storage-meta{font-size:11px;color:var(--text-2);margin-top:3px;overflow-wrap:anywhere}.extension-storage-actions-inline{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.extension-storage-status{margin-top:9px;font-size:12px;line-height:1.55}.extension-storage-status.ok{color:var(--success)}.extension-storage-status.error{color:var(--danger)}.extension-storage-status.warn{color:var(--warn)}
    .extension-backup-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center}.extension-backup-button{min-width:104px}.extension-backup-cloud-label{margin-top:13px}.extension-backup-help{margin-top:7px;color:var(--text-2);font-size:11px;line-height:1.5}
    @media(max-width:600px){.extension-storage-row{grid-template-columns:1fr}.extension-storage-actions-inline{justify-content:flex-start}.extension-backup-row{grid-template-columns:1fr}.extension-backup-button{width:100%}}
  `;document.head.appendChild(style);}

  function makeInput(labelText,id,type='text',value='',placeholder=''){const label=document.createElement('label');label.className='field-label';const span=document.createElement('span');span.className='field-label-text';span.textContent=labelText;const input=document.createElement('input');input.className='field';input.id=id;input.type=type;input.value=value||'';input.placeholder=placeholder||'';input.autocomplete=type==='password'?'off':'off';label.append(span,input);return {label,input};}
  function makeStorageSection(){const host=document.querySelector('#panel-sync .sync-section');if(!host||$('extensionStorageSettings'))return;if(host.querySelector('.btn-row.primary-actions')){ }const card=document.createElement('div');card.className='subcard extension-storage-settings';card.id='extensionStorageSettings';const title=document.createElement('div');title.className='subcard-title';title.textContent=text('title');const desc=document.createElement('p');desc.className='subcard-desc';desc.textContent=text('desc');card.append(title,desc);const grid=document.createElement('div');grid.className='extension-storage-grid';const backendLabel=document.createElement('label');backendLabel.className='field-label';const backendSpan=document.createElement('span');backendSpan.className='field-label-text';backendSpan.textContent=text('backend');const backend=document.createElement('select');backend.id='extensionStorageBackend';backend.className='field';for(const [value,label] of [['disabled',text('disabled')],['github',text('github')],['webdav',text('webdav')]]){const o=document.createElement('option');o.value=value;o.textContent=label;backend.append(o);}backendLabel.append(backendSpan,backend);grid.append(backendLabel);
    const repo=makeInput(text('repo'),'extensionStorageGithubRepo','text','','owner/repository');const branch=makeInput(text('branch'),'extensionStorageGithubBranch','text','','main');const gf=makeInput(text('folder'),'extensionStorageGithubFolder','text',DEFAULTS.githubFolder,'chromium-cloud-sync/extensions');const dav=makeInput(text('davUrl'),'extensionStorageWebdavUrl','url','','https://example.com/remote.php/dav/files/user');const df=makeInput(text('davFolder'),'extensionStorageWebdavFolder','text',DEFAULTS.webdavFolder,'/ChromiumCloudSync/extensions');const user=makeInput(text('user'),'extensionStorageWebdavUsername');const pass=makeInput(text('pass'),'extensionStorageWebdavPassword','password');grid.append(repo.label,branch.label,gf.label,dav.label,df.label,user.label,pass.label);card.append(grid);const note=document.createElement('div');note.className='extension-storage-note';note.textContent=text('lfs');card.append(note);const actions=document.createElement('div');actions.className='extension-storage-actions';const test=document.createElement('button');test.type='button';test.className='secondary';test.id='extensionStorageTest';test.textContent=text('test');const save=document.createElement('button');save.type='button';save.className='primary';save.id='extensionStorageSave';save.textContent=text('save');actions.append(test,save);card.append(actions);const status=document.createElement('div');status.id='extensionStorageStatus';status.className='extension-storage-status';status.hidden=true;card.append(status);const primary=host.querySelector('.btn-row.primary-actions');if(primary)host.insertBefore(card,primary);else host.append(card);backend.addEventListener('change',()=>refreshVisibility());test.addEventListener('click',async()=>{setBusy(test,true);try{const cfg=readForm();await testBackend(cfg);showStatus(text('tested'),'ok');}catch(e){showStatus(e.message||String(e),'error');}finally{setBusy(test,false);}});save.addEventListener('click',async()=>{setBusy(save,true);try{const cfg=readForm();if(cfg.backend==='github')await githubRepoInfo(cfg);if(cfg.backend==='webdav')await testBackend(cfg);await setSettings(cfg);showStatus(text('saved'),'ok');}catch(e){showStatus(e.message||String(e),'error');}finally{setBusy(save,false);}});loadForm({backend,gf,repo,branch,dav,df,user,pass});function refreshVisibility(){const g=backend.value==='github',d=backend.value==='webdav';repo.label.hidden=branch.label.hidden=gf.label.hidden=!g;dav.label.hidden=df.label.hidden=user.label.hidden=pass.label.hidden=!d;}refreshVisibility();
  }
  async function loadForm(els){const s=await getConfig();els.backend.value=s.backend||'disabled';els.repo.input.value=s.githubRepo||'';els.branch.input.value=s.githubBranch||'';els.gf.input.value=s.githubFolder||DEFAULTS.githubFolder;els.dav.input.value=s.webdavUrl||'';els.df.input.value=s.webdavFolder||DEFAULTS.webdavFolder;els.user.input.value=s.webdavUsername||'';els.pass.input.value=s.webdavPassword||'';}
  function readForm(){return {backend:$('extensionStorageBackend').value,githubRepo:normalizeRepo($('extensionStorageGithubRepo').value),githubBranch:String($('extensionStorageGithubBranch').value||'').trim(),githubFolder:normalizeFolder($('extensionStorageGithubFolder').value)||DEFAULTS.githubFolder,webdavUrl:String($('extensionStorageWebdavUrl').value||'').trim(),webdavFolder:normalizeDavFolder($('extensionStorageWebdavFolder').value)||DEFAULTS.webdavFolder,webdavUsername:String($('extensionStorageWebdavUsername').value||''),webdavPassword:String($('extensionStorageWebdavPassword').value||'')};}
  function setBusy(b,v){if(!b)return;b.disabled=v;b.setAttribute('aria-busy',String(v));}
  function showStatus(msg,kind){const e=$('extensionStorageStatus');if(!e)return;e.hidden=false;e.className=`extension-storage-status ${kind}`;e.textContent=msg;}

  async function ensureConfigForPopup(){const cfg=await getConfig();if(cfg.backend==='disabled')return cfg;if(cfg.backend==='webdav'&&!cfg.webdavUrl)throw Error(text('needDav'));if(cfg.backend==='github'&&!cfg.githubRepo)throw Error(text('needRepo'));return cfg;}
  async function listCloud(cfg){const index=await readIndex(cfg);return Array.isArray(index.backups)?index.backups.sort((a,b)=>String(b.storedAt||'').localeCompare(String(a.storedAt||''))):[];}
  async function renderPopup(){injectStyles();const card=$('extensionBackupCard'),list=$('extensionBackupList'),status=$('extensionBackupStatus');if(!card||!list)return;const title=$('extensionBackupTitle'),desc=$('extensionBackupDescription');if(title)title.textContent=text('title');if(desc)desc.textContent=text('desc');list.replaceChildren();if($('extensionPackageInput'))$('extensionPackageInput').remove();const input=document.createElement('input');input.type='file';input.accept='.crx,.zip,application/x-chrome-extension,application/zip';input.hidden=true;input.id='extensionPackageInputV2';document.body.append(input);card.append(input);let cfg;try{cfg=await ensureConfigForPopup();}catch(e){if(status){status.hidden=false;status.className='backup-status error-copy';status.textContent=e.message||String(e);}return;}if(cfg.backend==='disabled'){const h=document.createElement('div');h.className='extension-backup-help';h.textContent=text('desc');list.append(h);return;}
    const local=(await chrome.management.getAll()).filter(x=>x.type==='extension'&&x.id!==chrome.runtime.id&&x.installType!=='normal');const label=document.createElement('div');label.className='section-label';label.textContent=String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'已安装的第三方扩展':'Installed third-party extensions';list.append(label);if(!local.length){const e=document.createElement('div');e.className='empty';e.textContent=String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'未检测到第三方扩展。':'No third-party extensions detected.';list.append(e);}for(const ext of local){const row=document.createElement('div');row.className='extension-backup-row';const main=document.createElement('div');main.className='extension-storage-main';const name=document.createElement('div');name.className='extension-storage-name';name.textContent=ext.name||ext.id;const meta=document.createElement('div');meta.className='extension-storage-meta';meta.textContent=`v${ext.version} · ${ext.installType||'external'} · ${ext.id}`;main.append(name,meta);const b=document.createElement('button');b.className='secondary extension-backup-button';b.type='button';b.textContent=String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'备份文件':'Back up package';b.addEventListener('click',()=>{input.value='';input.dataset.id=ext.id;input.dataset.name=ext.name||ext.id;input.dataset.version=ext.version||'';input.click();});row.append(main,b);list.append(row);}
    try{const cloud=await listCloud(cfg);const label2=document.createElement('div');label2.className='section-label extension-backup-cloud-label';label2.textContent=String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'云端备份':'Cloud backups';list.append(label2);if(!cloud.length){const e=document.createElement('div');e.className='empty';e.textContent=String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'暂无文件备份。':'No package backups found.';list.append(e);}for(const item of cloud){const row=document.createElement('div');row.className='extension-storage-row';const main=document.createElement('div');main.className='extension-storage-main';const name=document.createElement('div');name.className='extension-storage-name';name.textContent=`${item.name||item.extensionId} · v${item.version||'?'}`;const meta=document.createElement('div');meta.className='extension-storage-meta';meta.textContent=`${item.fileName} · ${formatBytes(item.size||0)} · ${String(item.sha256||'').slice(0,12)}`;main.append(name,meta);const actions=document.createElement('div');actions.className='extension-storage-actions-inline';const d=document.createElement('button');d.className='secondary';d.type='button';d.textContent=String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'下载':'Download';d.addEventListener('click',async()=>{setBusy(d,true);try{const bytes=await loadPackage(cfg,item);const blob=new Blob([bytes],{type:/\.zip$/i.test(item.fileName)?'application/zip':'application/x-chrome-extension'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=item.fileName||`${safeSegment(item.name)}.crx`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500);}catch(e){if(status){status.hidden=false;status.className='backup-status error-copy';status.textContent=e.message||String(e);}}finally{setBusy(d,false);}});actions.append(d);row.append(main,actions);list.append(row);}}catch(e){const err=document.createElement('div');err.className='empty error-copy';err.textContent=e.message||String(e);list.append(err);}
    input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;setBusy(input,false);try{if(file.size>MAX_GITHUB_CONTENTS_BYTES&&cfg.backend==='github')throw Error(`File exceeds the browser-side GitHub upload limit (${formatBytes(MAX_GITHUB_CONTENTS_BYTES)}).`);if(file.size>MAX_REGULAR_GITHUB_BYTES&&cfg.backend==='github'&&status){status.hidden=false;status.className='backup-status warn';status.textContent=text('lfs');}const bytes=new Uint8Array(await file.arrayBuffer());const md={id:input.dataset.id,name:input.dataset.name,version:input.dataset.version};await writePackage(cfg,md,bytes,file.name);if(status){status.hidden=false;status.className='backup-status ok';status.textContent=`${String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'备份已保存':'Backup saved'}: ${file.name}`;}await renderPopup();}catch(e){if(status){status.hidden=false;status.className='backup-status error-copy';status.textContent=`${String(window.CCSyncI18n?.currentLanguage?.()||'en')==='zh-CN'?'备份失败':'Backup failed'}: ${e.message||String(e)}`;}}});
  }

  function initOptions(){injectStyles();makeStorageSection();}
  window.CCSyncExtensionStorage={initOptions,renderPopup,testBackend,getConfig,STORAGE_KEYS};
  if(location.pathname.endsWith('/popup.html'))document.addEventListener('DOMContentLoaded',()=>void renderPopup());
})();
