(function(){
  const K={
    backend:'extensionBackupBackend',repo:'extensionBackupGithubRepo',branch:'extensionBackupGithubBranch',githubFolder:'extensionBackupGithubFolder',
    githubToken:'extensionBackupGithubToken',webdavUrl:'extensionBackupWebdavUrl',webdavFolder:'extensionBackupWebdavFolder',webdavUser:'extensionBackupWebdavUsername',webdavPass:'extensionBackupWebdavPassword',selected:'extensionBackupSelectedIds'
  };
  const D={backend:'disabled',repo:'',branch:'',githubFolder:'',githubToken:'',webdavUrl:'',webdavFolder:'',webdavUser:'',webdavPass:'',selected:[]};
  const MAX=95*1024*1024;
  const $=id=>document.getElementById(id);
  const lang=()=>window.CCSyncI18n?.currentLanguage?.()||document.documentElement.lang||'en';
  const zh=()=>lang()==='zh-CN';
  const t=k=>({
    title:zh()?'第三方扩展云存储':'Third-party extension cloud storage',desc:zh()?'CRX / ZIP 包使用独立云存储，不写入同步 Gist。':'CRX / ZIP packages use a separate cloud store and never enter the sync Gist.',
    backend:zh()?'存储后端':'Storage backend',disabled:zh()?'关闭':'Disabled',github:zh()?'GitHub 私有仓库':'GitHub private repository',webdav:'WebDAV',
    repo:zh()?'GitHub 仓库':'GitHub repository',branch:zh()?'分支（可选）':'Branch (optional)',folder:zh()?'存储文件夹':'Storage folder',token:zh()?'扩展备份 Token':'Extension backup token',
    tokenHelp:zh()?'这里使用独立的 GitHub Token。建议创建 Fine-grained Token，只授权目标私有仓库的 Contents: Read and write。':'Use a separate GitHub Token here. A fine-grained token is recommended, limited to the target private repository with Contents: Read and write.',
    tokenCreate:zh()?'创建 GitHub Token':'Create GitHub token',save:zh()?'保存设置':'Save settings',test:zh()?'测试连接':'Test connection',saved:zh()?'设置已保存':'Settings saved',tested:zh()?'连接成功':'Connection successful',
    needRepo:zh()?'请输入 owner/repository 格式的 GitHub 仓库。':'Enter a GitHub repository in owner/repository format.',needWebdav:zh()?'请输入 WebDAV 地址。':'Enter a WebDAV URL.',
    privateRepo:zh()?'目标仓库必须是私有仓库。':'The target repository must be private.',notWritable:zh()?'该 Token 无法写入仓库，请确认 Contents 权限为 Read and write。':'This token cannot write to the repository. Grant Contents: Read and write.',
    permission:zh()?'WebDAV 需要允许访问填写的服务器地址。':'WebDAV needs permission to access the server origin you entered.',
    selectTitle:zh()?'选择要同步的扩展':'Choose extensions to back up',selectDesc:zh()?'勾选后，该扩展才会作为第三方扩展包的云备份目标。扩展设置本身不会同步。':'Only checked extensions are package-backup targets. Third-party extension settings are never synchronized.',
    all:zh()?'全选':'Select all',none:zh()?'全不选':'Clear all',saveSelection:zh()?'保存同步选择':'Save selection',selectionSaved:zh()?'同步选择已保存':'Selection saved',
    backup:zh()?'备份 CRX / ZIP':'Back up CRX / ZIP',download:zh()?'下载':'Download',cloud:zh()?'云端备份':'Cloud backups',noLocal:zh()?'未检测到其他扩展。':'No other extensions detected.',noBackups:zh()?'暂无云端扩展包。':'No cloud package backups found.',
    chooseFile:zh()?'请选择该扩展对应的 CRX 或 ZIP 文件。':'Choose the CRX or ZIP file for this extension.',manual:zh()?'浏览器不会向扩展开放已安装扩展的原始 CRX 文件读取权限，因此首次备份需要你手动选择包文件。':'Chromium does not expose installed extension package bytes to another extension, so the first backup requires you to select the package file manually.',
    folderPlaceholder:zh()?'留空 = 根目录':'Leave blank = root directory',davUrl:zh()?'WebDAV 地址':'WebDAV URL',davFolder:zh()?'WebDAV 文件夹':'WebDAV folder',user:zh()?'用户名':'Username',pass:zh()?'密码':'Password',
    status:zh()?'存储状态':'Storage status',enabled:zh()?'已启用':'Enabled',disabledStatus:zh()?'未启用':'Not enabled',selectedCount:zh()?'已选择 {count} 个扩展':'{count} extensions selected',
    max:zh()?'GitHub Contents API 当前限制为 95 MB；超过该大小的文件不会上传。':'The GitHub Contents API is capped at 95 MB here; larger files are rejected.'
  }[k]||k);
  const getCfg=async()=>({...D,...await CCSyncRuntime.storageGet(Object.values(K))});
  const normRepo=v=>String(v||'').trim().replace(/^https?:\/\/github\.com\//i,'').replace(/\.git$/i,'').replace(/^\/+|\/+$/g,'');
  const normFolder=v=>String(v||'').trim().replace(/^\/+|\/+$/g,'').replace(/\\+/g,'/');
  const normDav=v=>{let x=String(v||'').trim().replace(/\\/g,'/');if(!x)return'';if(!x.startsWith('/'))x='/'+x;return x.replace(/\/+/g,'/').replace(/\/$/,'')||'';};
  const join=(...p)=>p.filter(Boolean).map((x,i)=>i?String(x).replace(/^\/+|\/+$/g,''):String(x).replace(/\/+$/,'')).filter(Boolean).join('/');
  const seg=v=>String(v||'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)||'package';
  const b64=b=>{let s='',c=0x8000;for(let i=0;i<b.length;i+=c)s+=String.fromCharCode(...b.subarray(i,Math.min(i+c,b.length)));return btoa(s);};
  const text=b=>new TextDecoder().decode(b);const fmt=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
  const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  async function sha256(b){const d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
  const githubConfigToken=cfg=>String(cfg.githubToken||'').trim();
  async function github(path,opt={},tokenOverride=''){
    const token=githubConfigToken({githubToken:tokenOverride})||githubConfigToken(await CCSyncRuntime.storageGet(['extensionBackupGithubToken']));
    if(!token)throw Error(zh()?'尚未配置扩展备份用 GitHub Token。':'The extension-backup GitHub Token is not configured.');
    const r=await fetch(`https://api.github.com${path}`,{...opt,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',Authorization:`Bearer ${token}`,...(opt.headers||{})}});
    const raw=await r.text();let d=null;try{d=raw?JSON.parse(raw):null;}catch{d={raw};}
    if(!r.ok){const e=new Error(d?.message||`GitHub API HTTP ${r.status}`);e.status=r.status;throw e;}return d;
  }
  async function githubRaw(cfg,path){const token=githubConfigToken(cfg);if(!token)throw Error(zh()?'尚未配置扩展备份用 GitHub Token。':'The extension-backup GitHub Token is not configured.');const r=await fetch(`https://api.github.com${path}`,{headers:{Accept:'application/vnd.github.raw+json','X-GitHub-Api-Version':'2026-03-10',Authorization:`Bearer ${token}`}});if(!r.ok)throw Error(`GitHub API HTTP ${r.status}`);return new Uint8Array(await r.arrayBuffer());}
  async function githubInfo(cfg){const repo=normRepo(cfg.repo);if(!/^[^/]+\/[^/]+$/.test(repo))throw Error(t('needRepo'));const d=await github(`/repos/${repo}`,{},cfg.githubToken);if(!d.private)throw Error(t('privateRepo'));if(d.permissions&&!d.permissions.push)throw Error(t('notWritable'));return d;}
  async function githubFile(cfg,path){try{return await github(`/repos/${normRepo(cfg.repo)}/contents/${path}`,{},cfg.githubToken);}catch(e){if(e.status===404)return null;throw e;}}
  async function githubPut(cfg,path,bytes,message){if(bytes.length>MAX)throw Error(t('max'));const repo=normRepo(cfg.repo),old=await githubFile(cfg,path),body={message,content:b64(bytes)};if(cfg.branch)body.branch=String(cfg.branch).trim();if(old?.sha)body.sha=old.sha;await github(`/repos/${repo}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},cfg.githubToken);}
  async function githubReadJson(cfg,path,fallback){try{return JSON.parse(text(await githubRaw(cfg,`/repos/${normRepo(cfg.repo)}/contents/${path}`)));}catch(e){if(e.message.includes('HTTP 404'))return fallback;throw e;}}
  async function davPermission(url){const u=new URL(url),origin=`${u.origin}/*`;if(!chrome.permissions?.request)return true;if(await chrome.permissions.contains({origins:[origin]}))return true;return chrome.permissions.request({origins:[origin]});}
  const davAuth=(u,p)=>u||p?`Basic ${b64(new TextEncoder().encode(`${u}:${p}`))}`:'';
  async function dav(cfg,relative,opt={}){if(!await davPermission(cfg.webdavUrl))throw Error(t('permission'));const base=cfg.webdavUrl.replace(/\/+$/,'');const folder=normDav(cfg.webdavFolder);const root=base+(folder||'');const clean=String(relative||'').replace(/^\/+/, '');const url=root+(clean?`/${clean}`:'');const h={...(opt.headers||{})},a=davAuth(cfg.webdavUser,cfg.webdavPass);if(a)h.Authorization=a;return fetch(url,{...opt,headers:h});}
  async function davAt(cfg,path,opt={}){if(!await davPermission(cfg.webdavUrl))throw Error(t('permission'));const root=cfg.webdavUrl.replace(/\/+$/,'');const clean=String(path||'').replace(/^\/+/, '');const url=root+(clean?`/${clean}`:'');const h={...(opt.headers||{})},a=davAuth(cfg.webdavUser,cfg.webdavPass);if(a)h.Authorization=a;return fetch(url,{...opt,headers:h});}
  async function davMkdir(cfg,folder){const n=normDav(folder);if(!n)return;let cur='';for(const part of n.split('/').filter(Boolean)){cur+='/'+part;const r=await davAt(cfg,cur,{method:'MKCOL'});if([200,201,204,207,405,409].includes(r.status))continue;throw Error(`WebDAV MKCOL failed: HTTP ${r.status}`);}}
  async function davPut(cfg,relative,bytes,type='application/octet-stream'){const dir=String(relative).split('/').slice(0,-1).join('/');if(dir)await davMkdir(cfg,join(normDav(cfg.webdavFolder),dir));const r=await dav(cfg,relative,{method:'PUT',headers:{'Content-Type':type},body:bytes});if(!r.ok)throw Error(`WebDAV upload failed: HTTP ${r.status}`);}
  async function davGet(cfg,relative){const r=await dav(cfg,relative,{method:'GET'});if(!r.ok)throw Error(`WebDAV download failed: HTTP ${r.status}`);return new Uint8Array(await r.arrayBuffer());}
  async function readIndex(cfg){if(cfg.backend==='github')return githubReadJson(cfg,join(normFolder(cfg.githubFolder),'index.json'),{schemaVersion:2,backups:[]});try{return JSON.parse(text(await davGet(cfg,'index.json')));}catch(e){if(e.message.includes('HTTP 404'))return {schemaVersion:2,backups:[]};throw e;}}
  async function writeIndex(cfg,index){const bytes=new TextEncoder().encode(JSON.stringify(index,null,2));if(cfg.backend==='github')return githubPut(cfg,join(normFolder(cfg.githubFolder),'index.json'),bytes,'Update extension backup index');return davPut(cfg,'index.json',bytes,'application/json');}
  async function readSelection(cfg){if(cfg.backend==='disabled')return null;try{const path='selection.json',data=cfg.backend==='github'?await githubReadJson(cfg,join(normFolder(cfg.githubFolder),path),null):JSON.parse(text(await davGet(cfg,path)));return Array.isArray(data?.selectedIds)?data.selectedIds.map(String):null;}catch(e){if(e.message.includes('HTTP 404'))return null;throw e;}}
  async function writeSelection(cfg,ids){const payload={schemaVersion:1,updatedAt:new Date().toISOString(),selectedIds:[...new Set(ids.map(String))].sort()};const bytes=new TextEncoder().encode(JSON.stringify(payload,null,2));if(cfg.backend==='github')return githubPut(cfg,join(normFolder(cfg.githubFolder),'selection.json'),bytes,'Update extension backup selection');return davPut(cfg,'selection.json',bytes,'application/json');}
  async function putPackage(cfg,ext,bytes,fileName){const hash=await sha256(bytes),folder=join('extensions',seg(ext.id),`v${seg(ext.version||'unknown')}`),path=join(folder,seg(fileName)),item={extensionId:ext.id,name:ext.name||ext.id,version:ext.version||'',fileName,format:/\.zip$/i.test(fileName)?'zip':'crx',size:bytes.length,sha256:hash,path,storedAt:new Date().toISOString()};if(cfg.backend==='github'){const root=normFolder(cfg.githubFolder);await githubPut(cfg,join(root,path),bytes,`Back up ${ext.name||ext.id} v${ext.version||''}`);await githubPut(cfg,join(root,folder,'metadata.json'),new TextEncoder().encode(JSON.stringify({schemaVersion:1,type:'chromium-cloud-sync-extension-package',package:item},null,2)),'Update extension backup metadata');}else{await davPut(cfg,path,bytes);await davPut(cfg,join(folder,'metadata.json'),new TextEncoder().encode(JSON.stringify({schemaVersion:1,type:'chromium-cloud-sync-extension-package',package:item},null,2)),'application/json');}const index=await readIndex(cfg);index.schemaVersion=2;index.updatedAt=new Date().toISOString();index.backups=(Array.isArray(index.backups)?index.backups:[]).filter(x=>`${x.extensionId}:${x.version}:${x.sha256}`!==`${item.extensionId}:${item.version}:${item.sha256}`);index.backups.push(item);index.backups=index.backups.slice(-200);await writeIndex(cfg,index);return item;}
  async function getPackage(cfg,item){return cfg.backend==='github'?githubRaw(cfg,`/repos/${normRepo(cfg.repo)}/contents/${join(normFolder(cfg.githubFolder),item.path)}`):davGet(cfg,item.path);}
  async function test(cfg){if(cfg.backend==='disabled')return true;if(cfg.backend==='github'){await githubInfo(cfg);return true;}if(cfg.backend==='webdav'){if(!cfg.webdavUrl)throw Error(t('needWebdav'));const r=await dav(cfg,'index.json',{method:'GET'});if(![200,206,404].includes(r.status))throw Error(`WebDAV connection failed: HTTP ${r.status}`);return true;}throw Error('Unsupported storage backend.');}
  const saveSelectionLocal=ids=>CCSyncRuntime.storageSet({[K.selected]:[...new Set(ids.map(String))]});
  async function getInstalled(){return (await chrome.management.getAll()).filter(x=>x.type==='extension'&&x.id!==chrome.runtime.id).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id)));}
  function inputField(label,id,type='text',placeholder=''){const l=document.createElement('label');l.className='field-label';const s=document.createElement('span');s.className='field-label-text';s.textContent=label;const i=document.createElement('input');i.className='field';i.id=id;i.type=type;i.placeholder=placeholder;l.append(s,i);return{l,i};}
  function addStyle(){if($('ccsExtensionStorageStylesV2'))return;const s=document.createElement('style');s.id='ccsExtensionStorageStylesV2';s.textContent=`#extensionStorageSettings{margin-top:14px}.ccs-ext-grid{display:grid;gap:10px}.ccs-ext-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.ccs-ext-note{color:var(--text-2);font-size:12px;line-height:1.55;margin-top:8px}.ccs-ext-selection{margin-top:18px;border-top:1px solid var(--line);padding-top:14px}.ccs-ext-selection-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;flex-wrap:wrap}.ccs-ext-selection-tools{display:flex;gap:6px;flex-wrap:wrap}.ccs-ext-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--line)}.ccs-ext-row:first-child{border-top:0}.ccs-ext-main{min-width:0}.ccs-ext-name{font-size:13px;font-weight:600;overflow-wrap:anywhere}.ccs-ext-meta{font-size:11px;color:var(--text-2);margin-top:2px;overflow-wrap:anywhere}.ccs-ext-status{font-size:12px;line-height:1.55;margin-top:10px}.ccs-ext-status.ok{color:var(--success)}.ccs-ext-status.error{color:var(--danger)}.ccs-ext-cloud{margin-top:18px}.ccs-ext-cloud-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--line)}.ccs-ext-cloud-name{font-size:13px;font-weight:600}.ccs-ext-cloud-meta{font-size:11px;color:var(--text-2);margin-top:2px}.ccs-ext-storage-link{font-size:12px;margin-left:4px}.ccs-ext-token-wrap{display:flex;gap:8px;align-items:flex-end}.ccs-ext-token-wrap .field-label{flex:1}.ccs-ext-token-help{font-size:12px;line-height:1.55;color:var(--text-2)}.ccs-ext-disabled{opacity:.72}@media(max-width:600px){.ccs-ext-row{grid-template-columns:auto minmax(0,1fr)}.ccs-ext-row .secondary{grid-column:2;justify-self:start}.ccs-ext-cloud-row{grid-template-columns:1fr}.ccs-ext-token-wrap{align-items:stretch;flex-direction:column}}`;document.head.appendChild(s);}
  function fileInput(){let el=$('ccsExtensionPackageInput');if(el)return el;el=document.createElement('input');el.type='file';el.id='ccsExtensionPackageInput';el.accept='.crx,.zip,application/zip,application/x-chrome-extension';el.hidden=true;document.body.append(el);el.addEventListener('change',async()=>{const extId=el.dataset.extensionId;const extName=el.dataset.extensionName;const extVersion=el.dataset.extensionVersion;const selected=el.files?.[0];el.value='';if(!selected||!extId)return;const cfg=await getCfg();if(cfg.backend==='disabled'){alert(zh()?'请先启用第三方扩展云存储。':'Enable third-party extension cloud storage first.');return;}try{const button=document.querySelector(`[data-backup-for="${CSS.escape(extId)}"]`);if(button){button.disabled=true;button.textContent=zh()?'上传中…':'Uploading…';}await putPackage(cfg,{id:extId,name:extName,version:extVersion},new Uint8Array(await selected.arrayBuffer()),selected.name);await saveSelectionLocal([...((await CCSyncRuntime.storageGet([K.selected]))[K.selected]||[]),extId]);if(button){button.disabled=false;button.textContent=t('backup');}await render();}catch(e){alert(e.message||String(e));const button=document.querySelector(`[data-backup-for="${CSS.escape(extId)}"]`);if(button){button.disabled=false;button.textContent=t('backup');}}});return el;}
  function cfgFromUI(c){return{...c,backend:$('extensionStorageBackend')?.value||c.backend,repo:$('extensionStorageGithubRepo')?.value||'',branch:$('extensionStorageGithubBranch')?.value||'',githubFolder:$('extensionStorageGithubFolder')?.value||'',githubToken:$('extensionStorageGithubToken')?.value||'',webdavUrl:$('extensionStorageWebdavUrl')?.value||'',webdavFolder:$('extensionStorageWebdavFolder')?.value||'',webdavUser:$('extensionStorageWebdavUsername')?.value||'',webdavPass:$('extensionStorageWebdavPassword')?.value||''};}
  async function initOptions(){addStyle();fileInput();const host=$('extensionStorageHost');if(!host||$('extensionStorageSettings'))return;const cfg=await getCfg(),card=document.createElement('div');card.id='extensionStorageSettings';card.className='subcard';host.append(card);
    const h=document.createElement('div');h.className='subcard-title';h.textContent=t('title');const p=document.createElement('p');p.className='subcard-desc';p.textContent=t('desc');card.append(h,p);
    const grid=document.createElement('div');grid.className='ccs-ext-grid';
    const backend=inputField(t('backend'),'extensionStorageBackend');backend.i.outerHTML=`<select class="field" id="extensionStorageBackend"><option value="disabled">${esc(t('disabled'))}</option><option value="github">${esc(t('github'))}</option><option value="webdav">WebDAV</option></select>`;backend.i=backend.l.querySelector('select');
    const repo=inputField(t('repo'),'extensionStorageGithubRepo','text','owner/repository'),branch=inputField(t('branch'),'extensionStorageGithubBranch'),folder=inputField(t('folder'),'extensionStorageGithubFolder','text',t('folderPlaceholder')),token=inputField(t('token'),'extensionStorageGithubToken','password','github_pat_…');
    const davUrl=inputField(t('davUrl'),'extensionStorageWebdavUrl','url','https://example.com/dav'),davFolder=inputField(t('davFolder'),'extensionStorageWebdavFolder','text',t('folderPlaceholder')),user=inputField(t('user'),'extensionStorageWebdavUsername'),pass=inputField(t('pass'),'extensionStorageWebdavPassword','password');
    const tokenWrap=document.createElement('div');tokenWrap.className='ccs-ext-token-wrap';tokenWrap.append(token.l);const link=document.createElement('a');link.className='ccs-ext-storage-link';link.href='https://github.com/settings/personal-access-tokens/new?name=ChromiumCloudSync%20Extension%20Backup&description=Private%20CRX%20ZIP%20backup&contents=write&metadata=read';link.target='_blank';link.rel='noopener noreferrer';link.textContent=t('tokenCreate');token.l.append(document.createElement('span'));
    const tokenHelp=document.createElement('div');tokenHelp.className='ccs-ext-token-help';tokenHelp.textContent=t('tokenHelp');tokenHelp.append(' ',link);grid.append(backend.l,repo.l,branch.l,folder.l,tokenHelp,davUrl.l,davFolder.l,user.l,pass.l);card.append(grid);
    const actions=document.createElement('div');actions.className='ccs-ext-actions';const testBtn=document.createElement('button');testBtn.className='secondary';testBtn.type='button';testBtn.textContent=t('test');const saveBtn=document.createElement('button');saveBtn.className='primary';saveBtn.type='button';saveBtn.textContent=t('save');actions.append(testBtn,saveBtn);card.append(actions);
    const status=document.createElement('div');status.className='ccs-ext-status';status.hidden=true;card.append(status);
    const note=document.createElement('div');note.className='ccs-ext-note';note.textContent=t('manual');card.append(note);
    backend.i.value=cfg.backend;repo.i.value=cfg.repo;branch.i.value=cfg.branch;folder.i.value=cfg.githubFolder;token.i.value=cfg.githubToken;davUrl.i.value=cfg.webdavUrl;davFolder.i.value=cfg.webdavFolder;user.i.value=cfg.webdavUser;pass.i.value=cfg.webdavPass;
    const toggle=()=>{const mode=backend.i.value;const gh=mode==='github',dv=mode==='webdav';repo.l.hidden=!gh;branch.l.hidden=!gh;folder.l.hidden=!gh;tokenWrap.hidden=true;tokenHelp.hidden=!gh;davUrl.l.hidden=!dv;davFolder.l.hidden=!dv;user.l.hidden=!dv;pass.l.hidden=!dv;note.hidden=!mode||mode==='disabled';};
    backend.i.addEventListener('change',toggle);toggle();
    testBtn.addEventListener('click',async()=>{try{testBtn.disabled=true;status.hidden=false;status.className='ccs-ext-status';status.textContent=zh()?'正在测试…':'Testing…';await test(cfgFromUI(cfg));status.className='ccs-ext-status ok';status.textContent=t('tested');}catch(e){status.className='ccs-ext-status error';status.textContent=e.message||String(e);}finally{testBtn.disabled=false;}});
    saveBtn.addEventListener('click',async()=>{try{saveBtn.disabled=true;const next=cfgFromUI(cfg),data={
      [K.backend]:next.backend,[K.repo]:next.backend==='github'?normRepo(next.repo):'',[K.branch]:next.backend==='github'?String(next.branch).trim():'',[K.githubFolder]:next.backend==='github'?normFolder(next.githubFolder):'',[K.githubToken]:next.backend==='github'?String(next.githubToken).trim():'',[K.webdavUrl]:next.backend==='webdav'?String(next.webdavUrl).trim():'',[K.webdavFolder]:next.backend==='webdav'?normDav(next.webdavFolder):'',[K.webdavUser]:next.backend==='webdav'?String(next.webdavUser):'',[K.webdavPass]:next.backend==='webdav'?String(next.webdavPass):''
    };if(next.backend==='github')await githubInfo({...next,githubToken:String(next.githubToken).trim()});else if(next.backend==='webdav'&&!next.webdavUrl)throw Error(t('needWebdav'));await CCSyncRuntime.storageSet(data);status.hidden=false;status.className='ccs-ext-status ok';status.textContent=t('saved');await render();}catch(e){status.hidden=false;status.className='ccs-ext-status error';status.textContent=e.message||String(e);}finally{saveBtn.disabled=false;}});
  }
  async function render(){const card=$('extensionStorageSettings');if(!card)return;const cfg=await getCfg();card.querySelectorAll('.ccs-ext-selection,.ccs-ext-cloud').forEach(x=>x.remove());
    if(cfg.backend==='disabled'){return;}
    const installed=await getInstalled();let selected=Array.isArray(cfg.selected)?cfg.selected.map(String):[];const cloudSelected=await readSelection(cfg).catch(()=>null);if(Array.isArray(cloudSelected))selected=cloudSelected;else if(!selected.length)selected=installed.map(x=>x.id);
    const section=document.createElement('section');section.className='ccs-ext-selection';const head=document.createElement('div');head.className='ccs-ext-selection-head';const copy=document.createElement('div');const title=document.createElement('div');title.className='subcard-title';title.textContent=t('selectTitle');const desc=document.createElement('div');desc.className='ccs-ext-note';desc.textContent=t('selectDesc');copy.append(title,desc);const tools=document.createElement('div');tools.className='ccs-ext-selection-tools';const all=document.createElement('button');all.className='secondary';all.type='button';all.textContent=t('all');const none=document.createElement('button');none.className='secondary';none.type='button';none.textContent=t('none');const saveSel=document.createElement('button');saveSel.className='primary';saveSel.type='button';saveSel.textContent=t('saveSelection');tools.append(all,none,saveSel);head.append(copy,tools);section.append(head);
    const list=document.createElement('div');const checks=new Map();for(const ext of installed){const row=document.createElement('label');row.className='ccs-ext-row';const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.includes(ext.id);cb.dataset.extensionId=ext.id;checks.set(ext.id,cb);const main=document.createElement('div');main.className='ccs-ext-main';const name=document.createElement('div');name.className='ccs-ext-name';name.textContent=ext.name||ext.id;const meta=document.createElement('div');meta.className='ccs-ext-meta';meta.textContent=`v${ext.version||'?'} · ${ext.installType||'unknown'} · ${ext.id}`;main.append(name,meta);const b=document.createElement('button');b.className='secondary';b.type='button';b.textContent=t('backup');b.dataset.backupFor=ext.id;b.disabled=!cb.checked;b.addEventListener('click',e=>{e.preventDefault();if(!cb.checked)return;const input=fileInput();input.dataset.extensionId=ext.id;input.dataset.extensionName=ext.name||ext.id;input.dataset.extensionVersion=ext.version||'';input.click();});cb.addEventListener('change',()=>{b.disabled=!cb.checked;});row.append(cb,main,b);list.append(row);}section.append(list);card.append(section);
    const updateCount=()=>{const count=[...checks.values()].filter(x=>x.checked).length;saveSel.textContent=`${t('saveSelection')} · ${count}`;};all.addEventListener('click',()=>{checks.forEach(x=>{x.checked=true;const b=x.closest('.ccs-ext-row')?.querySelector('button');if(b)b.disabled=false;});updateCount();});none.addEventListener('click',()=>{checks.forEach(x=>{x.checked=false;const b=x.closest('.ccs-ext-row')?.querySelector('button');if(b)b.disabled=true;});updateCount();});checks.forEach(x=>x.addEventListener('change',updateCount));updateCount();saveSel.addEventListener('click',async()=>{const ids=[...checks.entries()].filter(([,x])=>x.checked).map(([id])=>id);await saveSelectionLocal(ids);await writeSelection(cfg,ids);saveSel.textContent=t('selectionSaved');setTimeout(updateCount,900);});
    const cloud=document.createElement('section');cloud.className='ccs-ext-cloud';const ct=document.createElement('div');ct.className='subcard-title';ct.textContent=t('cloud');cloud.append(ct);try{const index=await readIndex(cfg),backups=Array.isArray(index.backups)?index.backups.slice().reverse():[];if(!backups.length){const n=document.createElement('div');n.className='ccs-ext-note';n.textContent=t('noBackups');cloud.append(n);}for(const item of backups){const row=document.createElement('div');row.className='ccs-ext-cloud-row';const m=document.createElement('div');const n=document.createElement('div');n.className='ccs-ext-cloud-name';n.textContent=item.name||item.extensionId;const meta=document.createElement('div');meta.className='ccs-ext-cloud-meta';meta.textContent=`v${item.version||'?'} · ${fmt(item.size)} · ${(item.format||'file').toUpperCase()} · ${item.extensionId}`;m.append(n,meta);const b=document.createElement('button');b.className='secondary';b.type='button';b.textContent=t('download');b.addEventListener('click',async()=>{try{b.disabled=true;const bytes=await getPackage(cfg,item),blob=new Blob([bytes],{type:item.format==='zip'?'application/zip':'application/x-chrome-extension'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=seg(item.fileName||`${seg(item.name)}.${item.format||'crx'}`);document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){alert(e.message||String(e));}finally{b.disabled=false;}});row.append(m,b);cloud.append(row);}card.append(cloud);}catch(e){const n=document.createElement('div');n.className='ccs-ext-status error';n.textContent=e.message||String(e);cloud.append(n);card.append(cloud);}
  }
  async function init(){await initOptions();await render();}
  window.CCSyncExtensionStorage={initOptions,renderPopup:render,refresh:render};
  document.addEventListener('DOMContentLoaded',()=>void init().catch(e=>console.error('Extension storage init failed:',e)));
})();
