const DICT={
'en':{
 title:'User Guide',subtitle:'A local-first Chromium sync tool backed by GitHub Gist.',
 quickTitle:'Quick start',quickBody:'Open Settings, enter your GitHub Token, validate it, then create a new private Gist or bind an existing one. After that, use Sync now or enable automatic synchronization.',
 popupTitle:'Popup overview',popupBody:'The popup shows synchronization readiness, the current Gist, the last successful synchronization time, automatic-sync status, revision and conflict counts, and actions for syncing or restoring browser data. The popup also hides third-party package backups when that feature is disabled.',
 storageTitle:'What is synchronized',storageBody:'The shared sync state can contain open tabs and windows, tab groups, bookmarks, installed extension metadata, selected extension-local storage, device identity information, synchronization metadata, deletion tombstones, checksums, and conflict records.',storageNote:'The current synchronization payload is stored as normal JSON in the Gist. The repository retains compatibility code for older encrypted Gist formats, but current synchronization should not be described as end-to-end encrypted.',
 deviceTitle:'Device identity',deviceBody:'Each browser can have a user-defined device name such as “Home PC”, “Work Laptop”, or “Gaming Browser”. The name is used as the logical device identity during synchronization and is saved locally before being included in the next successful sync.',
 syncTitle:'Sync model',syncBody:'The sync engine keeps a local base snapshot and performs a three-way merge between base, local, and remote state. Stable synchronization IDs are used for tabs, windows, groups, and bookmarks. Deletions are represented by tombstones so removed items do not silently reappear. Conflicting field changes can remain visible for manual resolution.',
 autoTitle:'Automatic sync',autoBody:'Automatic synchronization is disabled by default and uses a five-minute interval by default. In Settings you can enable it and select 5, 10, 15, 30, or 60 minutes. Browser events only trigger background synchronization when automatic sync is enabled.',
 extensionTitle:'Third-party extension backups',extensionBody:'CRX and ZIP packages for extensions installed outside a browser store use a separate optional file-backup system. The available backends are Disabled, GitHub private repository, and WebDAV. When Disabled is selected, the GitHub repository, branch, folder, WebDAV credentials, connection controls, and explanatory storage notes are hidden, and the popup does not show the third-party backup card.',githubBody:'With GitHub private repository selected, only the GitHub repository, optional branch, and storage folder settings are shown. With WebDAV selected, only the WebDAV URL, folder, username, and password are shown.',packageBody:'Package backups are uploaded only after the user explicitly selects a CRX or ZIP file. GitHub Contents API uploads above 95 MB are rejected. Package installation always remains a manual browser action.',
 historyTitle:'History and rollback',historyBody:'GitHub Gist keeps the revision history for the synchronized state. The extension also keeps a local history index with up to 30 recent entries. The history page can inspect revisions and roll a selected version back as a new current revision.',
 settingsTitle:'Settings pages',settingsBody:'The Settings page is divided into Sync, Third-party extensions, and Local areas. Sync contains GitHub connection and automatic-sync controls, Third-party extensions contains package-backup configuration, and Local shows the current local status.',
 privacyTitle:'Privacy',privacyBody:'New sync Gists created by the extension are private. GitHub access uses your own Token. The current sync state is stored as JSON, so access to the Gist should be treated as access to the synchronized browser data. Third-party package backups use the separate backend you configure.',
 troubleTitle:'Troubleshooting',troubleBody:'If an older Gist uses a removed encrypted format, use a compatible older release to migrate it successfully. For current settings problems, reload the extension after an update and verify that the selected storage backend and GitHub credentials match the configuration shown in Settings.'
},
'zh-CN':{
 title:'用户指南',subtitle:'基于 GitHub Gist 的本地优先 Chromium 同步工具。',
 quickTitle:'快速开始',quickBody:'打开“设置”，填写 GitHub Token 并验证，然后创建新的私有 Gist 或绑定已有 Gist。完成后可以点击“立即同步”，也可以开启自动同步。',
 popupTitle:'Popup 界面',popupBody:'Popup 会显示同步状态、当前 Gist、最后一次成功同步时间、自动同步状态、Revision 和冲突数量，并提供同步与恢复操作。当第三方扩展文件备份关闭时，Popup 不会显示第三方扩展备份卡片。',
 storageTitle:'同步哪些内容',storageBody:'共享同步状态可以包含打开的标签页和窗口、标签组、书签、已安装扩展元数据、选定的扩展本地存储、设备身份信息、同步元数据、删除标记、校验和以及冲突记录。',storageNote:'当前同步载荷以普通 JSON 保存在 Gist 中。仓库仍保留对旧版加密 Gist 格式的兼容代码，但当前同步不应描述为端到端加密。',
 deviceTitle:'设备身份',deviceBody:'每个浏览器都可以设置用户自定义的设备名称，例如“家用电脑”“工作笔记本”或“游戏浏览器”。同步时会使用这个名称作为逻辑设备身份；名称先保存在本地，并在下一次成功同步时写入云端设备记录。',
 syncTitle:'同步模型',syncBody:'同步引擎保存本地基准快照，并在基准、本地和远程状态之间执行三方合并。标签页、窗口、标签组和书签使用稳定的同步 ID。删除会记录为 tombstone，避免已经删除的项目再次出现；真正的字段冲突可以保留并等待手动处理。',
 autoTitle:'自动同步',autoBody:'自动同步默认关闭，默认间隔为 5 分钟。在设置中可以开启，并选择 5、10、15、30 或 60 分钟。只有在启用自动同步后，浏览器事件才会触发后台同步。',
 extensionTitle:'第三方扩展备份',extensionBody:'对于浏览器商店之外安装的扩展，可以使用独立的 CRX / ZIP 文件备份功能。可选后端包括“关闭文件备份”“GitHub 私有仓库”和“WebDAV”。选择“关闭文件备份”后，GitHub 仓库、分支、文件夹、WebDAV 凭据、测试连接、保存设置以及相关说明都会隐藏，Popup 中也不会显示第三方扩展备份卡片。',githubBody:'选择 GitHub 私有仓库时，只显示 GitHub 仓库、可选分支和存储文件夹。选择 WebDAV 时，只显示 WebDAV 地址、文件夹、用户名和密码。',packageBody:'只有在用户主动选择 CRX 或 ZIP 文件后才会上传。GitHub Contents API 会拒绝超过 95 MB 的文件。扩展安装始终由用户手动完成。',
 historyTitle:'历史与回滚',historyBody:'GitHub Gist 保存同步状态的 Revision 历史。插件还会在本地维护最多 30 条历史索引记录。可以在同步历史页面查看版本，并将指定版本回滚为新的当前 Revision。',
 settingsTitle:'设置页面',settingsBody:'设置页面分为“同步”“第三方扩展”和“本地”三个区域。“同步”包含 GitHub 连接和自动同步控制；“第三方扩展”包含 CRX / ZIP 文件存储配置；“本地”显示当前本地状态。',
 privacyTitle:'隐私',privacyBody:'插件创建的同步 Gist 默认是私有的。访问 GitHub 使用你自己的 Token。由于当前同步状态以 JSON 保存，应将能够访问 Gist 视为能够访问同步的浏览器数据。第三方扩展文件备份使用你配置的独立后端。',
 troubleTitle:'故障排查',troubleBody:'如果旧版 Gist 使用已经移除的加密格式，请使用兼容的旧版本成功同步一次完成迁移。如果当前设置页面出现问题，请先重新加载扩展，并确认设置中的存储后端与 GitHub 凭据正确。'
}
};
function detect(){return[navigator.language,...(navigator.languages||[])].some(x=>/^zh(?:[-_]|$)/i.test(x))?'zh-CN':'en';}
function apply(){const s=localStorage.getItem('ccsync-guide-language')||'auto',l=s==='auto'?detect():(s==='zh-CN'?'zh-CN':'en'),d=DICT[l]||DICT.en;document.documentElement.lang=l;document.querySelectorAll('[data-guide]').forEach(e=>{const value=d[e.dataset.guide];if(value)e.textContent=value;});}
function setupChoiceSwitch(root,initialValue,onChange){if(!root)return;const bs=[...root.querySelectorAll('.choice-switch-option')],set=v=>{root.dataset.active=(v==='en'||v==='dark')?'right':'left';bs.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===v)));};set(initialValue);bs.forEach(b=>b.addEventListener('click',async()=>{const v=b.dataset.value;await onChange(v);set(v);}));}
(async()=>{const lang=document.getElementById('language');const s=await chrome.storage.local.get(['language']);if(lang){const lv=s.language&&s.language!=='auto'?s.language:detect();setupChoiceSwitch(lang,lv,async v=>{await chrome.storage.local.set({language:v});localStorage.setItem('ccsync-guide-language',v);apply();});}const theme=document.getElementById('theme');if(theme&&window.CCSyncTheme){await CCSyncTheme.initTheme();const tm=await CCSyncTheme.getTheme();const tv=tm==='dark'||tm==='light'?tm:(document.documentElement.dataset.theme||'light');setupChoiceSwitch(theme,tv,async v=>CCSyncTheme.setTheme(v));}apply();})();
