(function(){
  const K={backend:'extensionBackupBackend',repo:'extensionBackupGithubRepo',branch:'extensionBackupGithubBranch',folder:'extensionBackupGithubFolder',token:'extensionBackupGithubToken',davUrl:'extensionBackupWebdavUrl',davFolder:'extensionBackupWebdavFolder',davUser:'extensionBackupWebdavUsername',davPass:'extensionBackupWebdavPassword',selected:'extensionBackupSelectedIds'};
  const D={backend:'disabled',repo:'',branch:'',folder:'',token:'',davUrl:'',davFolder:'',davUser:'',davPass:'',selected:[]};
  const MAX=95*1024*1024;
  const $=id=>document.getElementById(id);
  const lang=()=>window.CCSyncI18n?.currentLanguage?.()||document.documentElement.lang||'en';
  const zh=()=>lang()==='zh-CN';
  const text={
    title:()=>zh()?'第三方扩展云存储':'Third-party extension cloud storage',
    desc:()=>zh()?'第三方扩展包使用独立云存储，不写入同步 Gist。':'Third-party extension packages use a separate cloud store and never enter the sync Gist.',
    panelTitle:()=>zh()?'第三方扩展包存储':'Third-party extension file storage',
    panelDesc:()=>zh()?'单独备份和管理第三方 CRX / ZIP 扩展包，不写入同步数据库。':'Back up and manage third-party CRX / ZIP packages separately from the sync database.',
    nav:()=>zh()?'第三方扩展':'Third-party extensions',
    backend:()=>zh()?'存储后端':'Storage backend',disabled:()=>zh()?'关闭':'Disabled',github:()=>zh()?'GitHub 私有仓库':'GitHub private repository',
    repo:()=>zh()?'GitHub 仓库':'GitHub repository',branch:()=>zh()?'分支（可选）':'Branch (optional)',folder:()=>zh()?'存储文件夹':'Storage folder',
    token:()=>zh()?'扩展备份 Token':'Extension backup Token',tokenHelp:()=>zh()?'建议创建 Fine-grained Token，仅授权目标私有仓库的 Contents: Read and write。':'Create a fine-grained token limited to the target private repository with Contents: Read and write.',tokenLink:()=>zh()?'创建 GitHub Token':'Create GitHub Token',
    davUrl:()=>zh()?'WebDAV 地址':'WebDAV URL',davFolder:()=>zh()?'WebDAV 文件夹':'WebDAV folder',user:()=>zh()?'用户名':'Username',pass:()=>zh()?'密码':'Password',
    test:()=>zh()?'测试连接':'Test connection',save:()=>zh()?'保存存储设置':'Save storage settings',saved:()=>zh()?'存储设置已保存':'Storage settings saved',tested:()=>zh()?'连接成功':'Connection successful',
    needRepo:()=>zh()?'请输入 owner/repository 格式的 GitHub 仓库。':'Enter the GitHub repository as owner/repository.',needToken:()=>zh()?'请配置扩展备份用 GitHub Token。':'Configure the extension-backup GitHub Token first.',privateRepo:()=>zh()?'目标仓库必须是私有仓库。':'The target repository must be private.',notWritable:()=>zh()?'该 Token 没有仓库写入权限，请确认 Contents 为 Read and write。':'This token cannot write to the repository. Grant Contents: Read and write.',needDav:()=>zh()?'请输入 WebDAV 地址。':'Enter a WebDAV URL.',permission:()=>zh()?'WebDAV 需要允许访问填写的服务器地址。':'WebDAV needs permission to access the configured server origin.',
    choose:()=>zh()?'选择要备份的扩展':'Choose extensions to back up',chooseDesc:()=>zh()?'这里选择的是第三方扩展包备份范围。扩展设置本身不会同步。':'This selects which third-party extension packages are backup targets. Extension settings are never synchronized.',
    all:()=>zh()?'全选':'Select all',none:()=>zh()?'全不选':'Clear all',saveSelection:()=>zh()?'保存备份选择':'Save backup selection',selectionSaved:()=>zh()?'备份选择已保存':'Backup selection saved',selectionNeedSave:()=>zh()?'请先保存存储设置，再保存扩展备份选择。':'Save the storage settings first, then save the extension backup selection.',
    backup:()=>zh()?'备份 CRX / ZIP':'Back up CRX / ZIP',download:()=>zh()?'下载':'Download',cloud:()=>zh()?'云端备份':'Cloud backups',noBackups:()=>zh()?'暂无云端扩展包。':'No cloud package backups found.',
    manual:()=>zh()?'浏览器无法从其他扩展直接读取已安装扩展的原始 CRX，因此首次备份需要手动选择 CRX 或 ZIP。':'The browser does not expose another extension’s installed CRX bytes, so the first backup requires manual selection of a CRX or ZIP file.',uploading:()=>zh()?'上传中…':'Uploading…',
    createToken:()=>zh()?'请先在 GitHub 创建 Fine-grained Token，再粘贴到这里。':'Create a fine-grained GitHub Token first, then paste it here.',max:()=>zh()?'超过 95 MB 的文件不会通过当前 GitHub Contents API 上传。':'Files larger than 95 MB are rejected by the current GitHub Contents API path.'
  };
  const t=k=>text[k]?.()||k;
  const getCfg=async()=>({...D,...await CCSyncRuntime.storageGet(Object.values(K))});
  const normRepo=v=>String(v||'').trim().replace(/^https?:\/\/github\.com\//i,'').replace(/\.git$/i,'').replace(/^\/+|\/+$/g,'');
  const normFolder=v=>String(v||'').trim().replace(/^\/+|\/+$/g,'').replace(/\\+/g,'/');
  const normDav=v=>{let x=String(v||'').trim().replace(/\\/g,'/');if(!x)return'';if(!x.startsWith('/'))x='/'+x;return x.replace(/\/+/g,'/').replace(/\/$/,'')||'';};
  const join=(...parts)=>parts.filter(Boolean).map((x,i)=>i?String(x).replace(/^\/+|\/+$/g,''):String(x).replace(/\/+$/,'')).filter(Boolean).join('/');
  const seg=v=>String(v||'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120)||'package';
  const bytes64=b=>{let s='',step=0x8000;for(let i=0;i<b.length;i+=step)s+=String.fromCharCode(...b.subarray(i,Math.min(i+step,b.length)));return btoa(s);};
  const decode=b=>new TextDecoder().decode(b); const fmt=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
  async function sha256(bytes){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
  async function github(path,opt={},token){const value=String(token||'').trim()||String((await CCSyncRuntime.storageGet([K.token]))[K.token]||'').trim();if(!value)throw Error(t('needToken'));const r=await fetch(`https://api.github.com${path}`,{...opt,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',Authorization:`Bearer ${value}`,...(opt.headers||{})}});const raw=await r.text();let data=null;try{data=raw?JSON.parse(raw):null;}catch{data={raw};}if(!r.ok){const e=new Error(data?.message||`GitHub API HTTP ${r.status}`);e.status=r.status;throw e;}return data;}
  async function githubInfo(cfg){const repo=normRepo(cfg.repo);if(!/^[^/]+\/[^/]+$/.test(repo))throw Error(t('needRepo'));const d=await github(`/repos/${repo}`,{},cfg.token);if(!d.private)throw Error(t('privateRepo'));if(d.permissions&&!d.permissions.push)throw Error(t('notWritable'));return d;}
  async function githubFile(cfg,path){try{return await github(`/repos/${normRepo(cfg.repo)}/contents/${path}`,{},cfg.token);}catch(e){if(e.status===404)return null;throw e;}}
  async function githubPut(cfg,path,bytes,message){if(bytes.length>MAX)throw Error(t('max'));const repo=normRepo(cfg.repo),old=await githubFile(cfg,path),body={message,content:bytes64(bytes)};if(cfg.branch)body.branch=String(cfg.branch).trim();if(old?.sha)body.sha=old.sha;await github(`/repos/${repo}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},cfg.token);}
  async function githubRaw(cfg,path){const r=await fetch(`https://api.github.com${path}`,{headers:{Accept:'application/vnd.github.raw+json','X-GitHub-Api-Version':'2026-03-10',Authorization:`Bearer ${cfg.token}`}});if(!r.ok)throw Error(`GitHub API HTTP ${r.status}`);return new Uint8Array(await r.arrayBuffer());}
  async function githubReadJson(cfg,path,fallback){try{return JSON.parse(decode(await githubRaw(cfg,`/repos/${normRepo(cfg.repo)}/contents/${path}`)));}catch(e){if(e.message.includes('HTTP 404'))return fallback;throw e;}}
  async function davPermission(url){const u=new URL(url),origin=`${u.origin}/*`;if(!chrome.permissions?.request)return true;if(await chrome.permissions.contains({origins:[origin]}))return true;return chrome.permissions.request({origins:[origin]});}
  const davAuth=(u,p)=>u||p?`Basic ${bytes64(new TextEncoder().encode(`${u}:${p}`))}`:'';
  async function dav(cfg,relative,opt={}){if(!await davPermission(cfg.davUrl))throw Error(t('permission'));const base=cfg.davUrl.replace(/\/+$/,'');const folder=normDav(cfg.davFolder);const root=base+(folder||'');const clean=String(relative||'').replace(/^\/+/, '');const url=root+(clean?`/${clean}`:'');const h={...(opt.headers||{})},a=davAuth(cfg.davUser,cfg.davPass);if(a)h.Authorization=a;return fetch(url,{...opt,headers:h});}
  async function davAt(cfg,path,opt={}){if(!await davPermission(cfg.davUrl))throw Error(t('permission'));const root=cfg.davUrl.replace(/\/+$/,'');const clean=String(path||'').replace(/^\/+/, '');const url=root+(clean?`/${clean}`:'');const h={...(opt.headers||{})},a=davAuth(cfg.davUser,cfg.davPass);if(a)h.Authorization=a;return fetch(url,{...opt,headers:h});}
  async function davMkdir(cfg,folder){const n=normDav(folder);if(!n)return;let cur='';for(const part of n.split('/').filter(Boolean)){cur+='/'+part;const r=await davAt(cfg,cur,{method:'MKCOL'});if([200,201,204,207,405,409].includes(r.status))continue;throw Error(`WebDAV MKCOL failed: HTTP ${r.status}`);}}
  async function davPut(cfg,relative,bytes,type='application/octet-stream'){const dir=String(relative).split('/').slice(0,-1).join('/');if(dir)await davMkdir(cfg,join(normDav(cfg.davFolder),dir));const r=await dav(cfg,relative,{method:'PUT',headers:{'Content-Type':type},body:bytes});if(!r.ok)throw Error(`WebDAV upload failed: HTTP ${r.status}`);}
  async function davGet(cfg,relative){const r=await dav(cfg,relative,{method:'GET'});if(!r.ok)throw Error(`WebDAV download failed: HTTP ${r.status}`);return new Uint8Array(await r.arrayBuffer());}
  async function readIndex(cfg){if(cfg.backend==='github')return githubReadJson(cfg,join(normFolder(cfg.folder),'index.json'),{schemaVersion:2,backups:[]});try{return JSON.parse(decode(await davGet(cfg,'index.json')));}catch(e){if(e.message.includes('HTTP 404'))return {schemaVersion:2,backups:[]};throw e;}}
  async function writeIndex(cfg,index){const bytes=new TextEncoder().encode(JSON.stringify(index,null,2));return cfg.backend==='github'?githubPut(cfg,join(normFolder(cfg.folder),'index.json'),bytes,'Update extension backup index'):davPut(cfg,'index.json',bytes,'application/json');}
  async function readSelection(cfg){if(cfg.backend==='github'){return githubReadJson(cfg,join(normFolder(cfg.folder),'selection.json'),null).then(x=>Array.isArray(x?.selectedIds)?x.selectedIds.map(String):null);}try{const x=JSON.parse(decode(await davGet(cfg,'selection.json')));return Array.isArray(x?.selectedIds)?x.selectedIds.map(String):null;}catch(e){if(e.message.includes('HTTP 404'))return null;throw e;}}
  async function writeSelection(cfg,ids){const payload={schemaVersion:1,updatedAt:new Date().toISOString(),selectedIds:[...new Set(ids.map(String))].sort()};const bytes=new TextEncoder().encode(JSON.stringify(payload,null,2));return cfg.backend==='github'?githubPut(cfg,join(normFolder(cfg.folder),'selection.json'),bytes,'Update extension backup selection'):davPut(cfg,'selection.json',bytes,'application/json');}
  async function putPackage(cfg,ext,bytes,fileName){const hash=await sha256(bytes),folder=join('extensions',seg(ext.id),`v${seg(ext.version||'unknown')}`),path=join(folder,seg(fileName)),item={extensionId:ext.id,name:ext.name||ext.id,version:ext.version||'',fileName,format:/\.zip$/i.test(fileName)?'zip':'crx',size:bytes.length,sha256:hash,path,storedAt:new Date().toISOString()};if(cfg.backend==='github'){const root=normFolder(cfg.folder);await githubPut(cfg,join(root,path),bytes,`Back up ${ext.name||ext.id} v${ext.version||''}`);await githubPut(cfg,join(root,folder,'metadata.json'),new TextEncoder().encode(JSON.stringify({schemaVersion:1,type:'chromium-cloud-sync-extension-package',package:item},null,2)),'Update extension backup metadata');}else{await davPut(cfg,path,bytes);await davPut(cfg,join(folder,'metadata.json'),new TextEncoder().encode(JSON.stringify({schemaVersion:1,type:'chromium-cloud-sync-extension-package',package:item},null,2)),'application/json');}const index=await readIndex(cfg);index.schemaVersion=2;index.updatedAt=new Date().toISOString();index.backups=(Array.isArray(index.backups)?index.backups:[]).filter(x=>`${x.extensionId}:${x.version}:${x.sha256}`!==`${item.extensionId}:${item.version}:${item.sha256}`);index.backups.push(item);index.backups=index.backups.slice(-200);await writeIndex(cfg,index);return item;}
  async function getPackage(cfg,item){return cfg.backend==='github'?githubRaw(cfg,`/repos/${normRepo(cfg.repo)}/contents/${join(normFolder(cfg.folder),item.path)}`):davGet(cfg,item.path);}
  async function test(cfg){if(cfg.backend==='disabled')return true;if(cfg.backend==='github'){await githubInfo(cfg);return true;}if(cfg.backend==='webdav'){if(!cfg.davUrl)throw Error(t('needDav'));const r=await dav(cfg,'index.json',{method:'GET'});if(![200,206,404].includes(r.status))throw Error(`WebDAV connection failed: HTTP ${r.status}`);return true;}throw Error('Unsupported storage backend.');}
  async function getInstalled(){return(await chrome.management.getAll()).filter(x=>x.type==='extension'&&x.id!==chrome.runtime.id).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id)));}
  function field(label,id,type='text',placeholder=''){const l=document.createElement('label');l.className='field-label';const s=document.createElement('span');s.className='field-label-text';s.textContent=label;const i=document.createElement('input');i.className='field';i.id=id;i.type=type;i.placeholder=placeholder;l.append(s,i);return{l,i,s};}
  function addStyles(){if($('ccsync-extension-storage-styles'))return;const s=document.createElement('style');s.id='ccsync-extension-storage-styles';s.textContent='.ccsync-ext-grid{display:grid;gap:10px}.ccsync-ext-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.ccsync-ext-note{color:var(--text-2);font-size:12px;line-height:1.55;margin-top:8px}.ccsync-ext-selection,.ccsync-ext-cloud{margin-top:18px;border-top:1px solid var(--line);padding-top:14px}.ccsync-ext-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.ccsync-ext-tools{display:flex;gap:6px;flex-wrap:wrap}.ccsync-ext-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--line)}.ccsync-ext-row:first-child{border-top:0}.ccsync-ext-name{font-size:13px;font-weight:600;overflow-wrap:anywhere}.ccsync-ext-meta{font-size:11px;color:var(--text-2);margin-top:2px;overflow-wrap:anywhere}.ccsync-ext-status{font-size:12px;line-height:1.55;margin-top:10px}.ccsync-ext-status.ok{color:var(--success)}.ccsync-ext-status.error{color:var(--danger)}.ccsync-ext-cloud-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid var(--line)}.ccsync-ext-cloud-name{font-size:13px;font-weight:600}.ccsync-ext-cloud-meta{font-size:11px;color:var(--text-2);margin-top:2px}.ccsync-ext-token-help{font-size:12px;line-height:1.55;color:var(--text-2)}.ccsync-ext-hidden{display:none!important}@media(max-width:600px){.ccsync-ext-row,.ccsync-ext-cloud-row{grid-template-columns:1fr}.ccsync-ext-row input[type=checkbox]{justify-self:start}.ccsync-ext-row .secondary{justify-self:start}}';document.head.appendChild(s);}
  function setHidden(el,hidden){if(!el)return;el.hidden=hidden;el.classList.toggle('ccsync-ext-hidden',hidden);}
  function fileInput(){let input=$('ccsyncExtensionPackageInput');if(input)return input;input=document.createElement('input');input.type='file';input.id='ccsyncExtensionPackageInput';input.accept='.crx,.zip,application/zip,application/x-chrome-extension';input.hidden=true;document.body.append(input);input.addEventListener('change',async()=>{const id=input.dataset.extensionId,name=input.dataset.extensionName,version=input.dataset.extensionVersion,file=input.files?.[0];input.value='';if(!id||!file)return;const cfg=await getCfg();if(cfg.backend==='disabled'){alert(zh()?'请先保存并启用第三方扩展云存储。':'Save and enable third-party extension cloud storage first.');return;}const button=document.querySelector(`[data-backup-for="${CSS.escape(id)}"]`);try{if(button){button.disabled=true;button.textContent=t('uploading');}await putPackage(cfg,{id,name,version},new Uint8Array(await file.arrayBuffer()),file.name);const selected=new Set(cfg.selected);selected.add(id);await CCSyncRuntime.storageSet({[K.selected]:[...selected]});if(button){button.disabled=false;button.textContent=t('backup');}await render(cfg);}catch(e){if(button){button.disabled=false;button.textContent=t('backup');}alert(e.message||String(e));}});return input;}
  function uiCfg(saved){return{...saved,backend:$('extensionStorageBackend')?.value||saved.backend,repo:$('extensionStorageGithubRepo')?.value?.trim()||'',branch:$('extensionStorageGithubBranch')?.value?.trim()||'',folder:$('extensionStorageGithubFolder')?.value?.trim()||'',token:$('extensionStorageGithubToken')?.value?.trim()||'',davUrl:$('extensionStorageWebdavUrl')?.value?.trim()||'',davFolder:$('extensionStorageWebdavFolder')?.value?.trim()||'',davUser:$('extensionStorageWebdavUsername')?.value||'',davPass:$('extensionStorageWebdavPassword')?.value||''};}
  function sameStorageConfig(a,b){if(!a||!b||a.backend!==b.backend)return false;if(a.backend==='github')return normRepo(a.repo)===normRepo(b.repo)&&String(a.branch||'').trim()===String(b.branch||'').trim()&&normFolder(a.folder)===normFolder(b.folder)&&String(a.token||'').trim()===String(b.token||'').trim();if(a.backend==='webdav')return String(a.davUrl||'').trim()===String(b.davUrl||'').trim()&&normDav(a.davFolder)===normDav(b.davFolder)&&String(a.davUser||'')===String(b.davUser||'')&&String(a.davPass||'')===String(b.davPass||'');return true;}
  let refreshLanguage=()=>{};
  async function initOptions(){addStyles();fileInput();const host=$('extensionStorageHost');if(!host||$('extensionStorageSettings'))return;try{await window.CCSyncI18n?.initI18n?.();}catch{}const saved=await getCfg();const card=document.createElement('div');card.id='extensionStorageSettings';card.className='subcard';host.append(card);
    const title=document.createElement('div');title.className='subcard-title';const desc=document.createElement('p');desc.className='subcard-desc';card.append(title,desc);
    const grid=document.createElement('div');grid.className='ccsync-ext-grid';
    const backend=field(t('backend'),'extensionStorageBackend');backend.i.outerHTML=`<select class="field" id="extensionStorageBackend"><option value="disabled">${t('disabled')}</option><option value="github">${t('github')}</option><option value="webdav">WebDAV</option></select>`;backend.i=backend.l.querySelector('select');
    const repo=field(t('repo'),'extensionStorageGithubRepo','text','owner/repository'),branch=field(t('branch'),'extensionStorageGithubBranch'),folder=field(t('folder'),'extensionStorageGithubFolder','text',zh()?'留空 = 根目录':'Leave blank = root directory'),token=field(t('token'),'extensionStorageGithubToken','password','github_pat_…');
    const tokenHelp=document.createElement('div');tokenHelp.className='ccsync-ext-token-help';const tokenLink=document.createElement('a');tokenLink.href='https://github.com/settings/personal-access-tokens/new?name=ChromiumCloudSync%20Extension%20Backup&description=Private%20CRX%20ZIP%20backup';tokenLink.target='_blank';tokenLink.rel='noopener noreferrer';tokenLink.className='ccsync-ext-storage-link';tokenHelp.append(tokenLink);
    const davUrl=field(t('davUrl'),'extensionStorageWebdavUrl','url','https://example.com/dav'),davFolder=field(t('davFolder'),'extensionStorageWebdavFolder','text',zh()?'留空 = 根目录':'Leave blank = root directory'),user=field(t('user'),'extensionStorageWebdavUsername'),pass=field(t('pass'),'extensionStorageWebdavPassword','password');
    grid.append(backend.l,repo.l,branch.l,folder.l,token.l,tokenHelp,davUrl.l,davFolder.l,user.l,pass.l);card.append(grid);
    const actions=document.createElement('div');actions.className='ccsync-ext-actions';const testBtn=document.createElement('button');testBtn.className='secondary';testBtn.type='button';const saveBtn=document.createElement('button');saveBtn.className='primary';saveBtn.type='button';actions.append(testBtn,saveBtn);card.append(actions);
    const status=document.createElement('div');status.className='ccsync-ext-status';status.hidden=true;card.append(status);const note=document.createElement('div');note.className='ccsync-ext-note';card.append(note);
    backend.i.value=saved.backend;repo.i.value=saved.repo;branch.i.value=saved.branch;folder.i.value=saved.folder;token.i.value=saved.token;davUrl.i.value=saved.davUrl;davFolder.i.value=saved.davFolder;user.i.value=saved.davUser;pass.i.value=saved.davPass;
    const refreshOuterText=()=>{const nav=$('extensionStorageNavLabel'),pt=$('extensionStoragePanelTitle'),pd=$('extensionStoragePanelDescription');if(nav)nav.textContent=t('nav');if(pt)pt.textContent=t('panelTitle');if(pd)pd.textContent=t('panelDesc');};
    const refreshSettingsText=()=>{refreshOuterText();title.textContent=t('title');desc.textContent=t('desc');backend.s.textContent=t('backend');backend.i.querySelector('option[value="disabled"]').textContent=t('disabled');backend.i.querySelector('option[value="github"]').textContent=t('github');repo.s.textContent=t('repo');branch.s.textContent=t('branch');folder.s.textContent=t('folder');token.s.textContent=t('token');tokenHelp.textContent=t('tokenHelp');tokenHelp.append(' ',tokenLink);tokenLink.textContent=t('tokenLink');davUrl.s.textContent=t('davUrl');davFolder.s.textContent=t('davFolder');user.s.textContent=t('user');pass.s.textContent=t('pass');testBtn.textContent=t('test');saveBtn.textContent=t('save');note.textContent=t('manual');for(const input of [folder.i,davFolder.i])input.placeholder=zh()?'留空 = 根目录':'Leave blank = root directory';};
    const toggle=()=>{const mode=backend.i.value,gh=mode==='github',dv=mode==='webdav',active=gh||dv;for(const el of [repo.l,branch.l,folder.l,token.l,tokenHelp])setHidden(el,!gh);for(const el of [davUrl.l,davFolder.l,user.l,pass.l])setHidden(el,!dv);setHidden(actions,!active);setHidden(note,!active);};
    const refreshVisible=async()=>{toggle();await render(uiCfg(await getCfg()));};
    backend.i.addEventListener('change',()=>void refreshVisible());toggle();refreshSettingsText();
    refreshLanguage=async()=>{refreshSettingsText();toggle();const current=await getCfg();await render(uiCfg(current));};
    testBtn.addEventListener('click',async()=>{try{testBtn.disabled=true;status.hidden=false;status.className='ccsync-ext-status';status.textContent=zh()?'正在测试…':'Testing…';await test(uiCfg(saved));status.className='ccsync-ext-status ok';status.textContent=t('tested');}catch(e){status.className='ccsync-ext-status error';status.textContent=e.message||String(e);}finally{testBtn.disabled=false;}});
    saveBtn.addEventListener('click',async()=>{try{saveBtn.disabled=true;const next=uiCfg(saved);if(next.backend==='github'){next.repo=normRepo(next.repo);next.folder=normFolder(next.folder);if(!next.token)throw Error(t('needToken'));await githubInfo(next);}else if(next.backend==='webdav'){next.davUrl=String(next.davUrl).trim();next.davFolder=normDav(next.davFolder);if(!next.davUrl)throw Error(t('needDav'));}else{next.repo='';next.branch='';next.folder='';next.token='';next.davUrl='';next.davFolder='';next.davUser='';next.davPass='';}await CCSyncRuntime.storageSet({[K.backend]:next.backend,[K.repo]:next.repo,[K.branch]:next.branch,[K.folder]:next.folder,[K.token]:next.token,[K.davUrl]:next.davUrl,[K.davFolder]:next.davFolder,[K.davUser]:next.davUser,[K.davPass]:next.davPass});Object.assign(saved,next);status.hidden=false;status.className='ccsync-ext-status ok';status.textContent=t('saved');refreshSettingsText();toggle();await render({...saved});}catch(e){status.hidden=false;status.className='ccsync-ext-status error';status.textContent=e.message||String(e);}finally{saveBtn.disabled=false;}});
  }
  async function render(cfg){const card=$('extensionStorageSettings');if(!card)return;card.querySelectorAll('.ccsync-ext-selection,.ccsync-ext-cloud').forEach(x=>x.remove());if(!cfg||cfg.backend==='disabled')return;const installed=await getInstalled();let selected=Array.isArray(cfg.selected)?cfg.selected.map(String):[];let remote=null;const persisted=await getCfg();if(sameStorageConfig(cfg,persisted)){try{remote=await readSelection(cfg);}catch{remote=null;}}if(Array.isArray(remote))selected=remote;else if(!selected.length)selected=installed.map(x=>x.id);
    const section=document.createElement('section');section.className='ccsync-ext-selection';const head=document.createElement('div');head.className='ccsync-ext-head';const copy=document.createElement('div');const title=document.createElement('div');title.className='subcard-title';title.textContent=t('choose');const desc=document.createElement('div');desc.className='ccsync-ext-note';desc.textContent=t('chooseDesc');copy.append(title,desc);const tools=document.createElement('div');tools.className='ccsync-ext-tools';const all=document.createElement('button');all.className='secondary';all.type='button';all.textContent=t('all');const none=document.createElement('button');none.className='secondary';none.type='button';none.textContent=t('none');const saveSel=document.createElement('button');saveSel.className='primary';saveSel.type='button';saveSel.textContent=t('saveSelection');tools.append(all,none,saveSel);head.append(copy,tools);section.append(head);
    const list=document.createElement('div');const checks=new Map();for(const ext of installed){const row=document.createElement('label');row.className='ccsync-ext-row';const cb=document.createElement('input');cb.type='checkbox';cb.checked=selected.includes(ext.id);cb.dataset.extensionId=ext.id;const main=document.createElement('div');const name=document.createElement('div');name.className='ccsync-ext-name';name.textContent=ext.name||ext.id;const meta=document.createElement('div');meta.className='ccsync-ext-meta';meta.textContent=`v${ext.version||'?'} · ${ext.installType||'unknown'} · ${ext.id}`;main.append(name,meta);const b=document.createElement('button');b.className='secondary';b.type='button';b.textContent=t('backup');b.dataset.backupFor=ext.id;b.disabled=!cb.checked;b.addEventListener('click',e=>{e.preventDefault();void getCfg().then(s=>{if(!sameStorageConfig(s,cfg)){alert(t('selectionNeedSave'));return;}const input=fileInput();input.dataset.extensionId=ext.id;input.dataset.extensionName=ext.name||ext.id;input.dataset.extensionVersion=ext.version||'';input.click();});});cb.addEventListener('change',()=>{b.disabled=!cb.checked;updateCount();});checks.set(ext.id,cb);row.append(cb,main,b);list.append(row);}section.append(list);card.append(section);
    function updateCount(){const n=[...checks.values()].filter(x=>x.checked).length;saveSel.textContent=`${t('saveSelection')} · ${n}`;}
    all.addEventListener('click',()=>{checks.forEach(cb=>{cb.checked=true;const b=cb.closest('.ccsync-ext-row')?.querySelector('button');if(b)b.disabled=false;});updateCount();});none.addEventListener('click',()=>{checks.forEach(cb=>{cb.checked=false;const b=cb.closest('.ccsync-ext-row')?.querySelector('button');if(b)b.disabled=true;});updateCount();});saveSel.addEventListener('click',async()=>{try{const current=await getCfg();if(!sameStorageConfig(current,cfg))throw Error(t('selectionNeedSave'));const ids=[...checks.entries()].filter(([,cb])=>cb.checked).map(([id])=>id);await CCSyncRuntime.storageSet({[K.selected]:ids});await writeSelection(cfg,ids);saveSel.textContent=t('selectionSaved');setTimeout(updateCount,900);}catch(e){alert(e.message||String(e));}});updateCount();
    const cloud=document.createElement('section');cloud.className='ccsync-ext-cloud';const ct=document.createElement('div');ct.className='subcard-title';ct.textContent=t('cloud');cloud.append(ct);try{const index=await readIndex(cfg),backups=Array.isArray(index.backups)?index.backups.slice().reverse():[];if(!backups.length){const n=document.createElement('div');n.className='ccsync-ext-note';n.textContent=t('noBackups');cloud.append(n);}for(const item of backups){const row=document.createElement('div');row.className='ccsync-ext-cloud-row';const m=document.createElement('div'),n=document.createElement('div'),meta=document.createElement('div');n.className='ccsync-ext-cloud-name';n.textContent=item.name||item.extensionId;meta.className='ccsync-ext-cloud-meta';meta.textContent=`v${item.version||'?'} · ${fmt(item.size)} · ${(item.format||'file').toUpperCase()} · ${item.extensionId}`;m.append(n,meta);const b=document.createElement('button');b.className='secondary';b.type='button';b.textContent=t('download');b.addEventListener('click',async()=>{try{b.disabled=true;const bytes=await getPackage(cfg,item),blob=new Blob([bytes],{type:item.format==='zip'?'application/zip':'application/x-chrome-extension'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=seg(item.fileName||`${seg(item.name)}.${item.format||'crx'}`);document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){alert(e.message||String(e));}finally{b.disabled=false;}});row.append(m,b);cloud.append(row);}card.append(cloud);}catch(e){const n=document.createElement('div');n.className='ccsync-ext-status error';n.textContent=e.message||String(e);cloud.append(n);card.append(cloud);}}
  window.CCSyncExtensionStorage={initOptions,renderPopup:render,refresh:render,refreshLanguage:()=>refreshLanguage()};
  window.addEventListener('ccsync:language-changed',()=>void refreshLanguage());
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>void initOptions().catch(e=>console.error('Extension storage init failed:',e)));else void initOptions().catch(e=>console.error('Extension storage init failed:',e));
})();